language: c
compiler: clang

cache:
  directories:
  - $HOME/.opam/

script: 
  - ./compile.sh

notifications:
  email: false

before_install:
  - opam init -y --compiler=4.10.1
  - eval `opam config env`
  - opam install -y dune ocamlfind menhir
  - sudo chmod +x compile.sh

matrix:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - opam
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
